<!--section>
    <div class="row">
        <div class="col-md-12">
            <h3><?php echo $this->translate("Inicio"); ?></h3>
            <hr />
        </div>
    </div>
</section-->

<!--  -->
<section class="intro">
    <div class="row">
        <div class="col-md-12">

            <form class="navbar-form" role="search" method="get" action="<?php echo $this->url(array('controller' => 'busca')); ?>">
                <div class="form-group">
                    <input type="text" class="form-control" name="busca" placeholder="Busque por produtos ou serviços...">
                </div>
                <button type="submit" class="btn btn-default">Buscar <i class="fa fa-search"></i></button>
            </form>
                      
        </div>
    </div>
</section>

<!-- Buscas mais populares -->
<div class="container" id="">
    <section>
        <div class="row">
            <div class="col-md-12">
                <h3><?php echo $this->translate("Buscas mais populares"); ?></h3>
            </div>
        </div>    
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <?php foreach ($this->servicos as $servico) : ?>
                        <span class="label label-info tags">
                            <a href="<?php echo $this->url(array(
                                'controller' => 'busca',
                                'action' => 'index',
                                'busca' => $servico->servico_tag
                            ), null, true); ?>" class=""><?php echo $servico->servico_tag; ?></a>
                        </span>
                        <?php endforeach; ?>
                    </div>
                </div>            
            </div>
        </div>
    </section>
</div>
    
