<script>
    $(document).ready(function(){
       
    });
    function verTelefone(id) {
        $("#telefone_" + id).show();
    }
</script>

<div class="container" id="">

<section>
    <div class="row">
        <div class="col-md-9">
            <div class="row">
                <div class="col-md-12">
                    <h3><?php echo $this->translate("Produtos e serviços"); ?></h3>
                    <hr />
                </div>
            </div>
            <?php if ($this->servicos->count() > 0) : ?>
            <div class="row">        
                <?php foreach ($this->servicos as $servico) : ?>
                <div class="col-md-4">
                    <div class="well">  
                        <div class="row">
                            <div class="col-lg-6">
                                <!--<span class="small"><i class="fa fa-bookmark"></i> Serviço</span>-->
                            </div>
                            <div class="col-lg-6 text-right">
                                <i class="fa fa-star text-warning"></i>
                                <i class="fa fa-star text-warning"></i>
                                <i class="fa fa-star text-warning"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                            </div>           
                        </div>
                        <div class="row">
                            <div class="col-lg-12 small">
                                <hr />
                                <?php if ($servico->empresa_nome) : ?>
                                <h5><i class="fa fa-home"></i> <?php echo $servico->empresa_nome; ?></h5>
                                <?php endif; ?>
                                <h5><i class="fa fa-user"></i> <?php echo $servico->empresa_responsavel; ?></h5>
                                <p class=""><i class="fa fa-tags"></i> <?php echo $this->servico($servico->empresa_servico); ?></p>
                                <p class=""><i class="fa fa-map-marker"></i> 
                                    <?php echo $servico->empresa_endereco; ?>,
                                    <?php echo $servico->empresa_numero; ?> - 
                                    <?php echo $servico->empresa_complemento; ?>,
                                    <?php echo $servico->empresa_bairro; ?>
                                </p>                        
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <hr />
                                <p class="text-right">                    
                                    <a href="#" onclick="verTelefone(<?php echo $servico->empresa_id; ?>);">Ver telefones</a>
                                </p>
                                <div style="display: none;" id="telefone_<?php echo $servico->empresa_id; ?>">
                                    <h4>
                                        <i class="fa fa-phone"></i> 
                                        <?php echo $servico->empresa_telefone; ?><br />
                                    </h4>
                                    <h4>
                                        <i class="fa fa-phone-square"></i> 
                                        <?php echo $servico->empresa_celular; ?><br />
                                    </h4>               
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
            <?php else : ?>
            <div class="row">        
                <div class="col-lg-12">
                    <div class="alert alert-warning">Nenhum serviço encontrado</div>
                </div>        
            </div>
            <?php endif; ?>
        </div>

        <div class="col-md-3">
            <h4>box de anuncios pagos</h4>
            <hr>
            <h4>newsletter</h4>
            <hr>
            <h4>adsense</h4>
            <hr>
            <h4>cadastre-se</h4>
            <hr>
            <h4>anuncie aqui</h4>
        </div>
    </div>
</section>

</div> <!-- /container -->
