<script>
    $(document).ready(function(){
       
    });
    function verTelefone(id) {
        $("#telefone_" + id).show();
    }
</script>
<section>
    <div class="row">
        <div class="col-md-12">
            <h3><?php echo $this->translate("Produtos e serviços"); ?></h3>
            <hr />
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="well">  
                <div class="row">
                    <div class="col-lg-6">
                        <span class="small"><i class="fa fa-tag"></i> Serviço</span>
                    </div>
                    <div class="col-lg-6 text-right">
                        <i class="fa fa-star text-warning"></i>
                        <i class="fa fa-star text-warning"></i>
                        <i class="fa fa-star text-warning"></i>
                        <i class="fa fa-star-o"></i>
                        <i class="fa fa-star-o"></i>
                    </div>           
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <hr />
                        <h5><i class="fa fa-user"></i> Mário Bombeiro Hidráulico</h5>
                        <span class=""><i class="fa fa-map-marker"></i> Rua X, 128 - Sarzedo</span><br />                
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <hr />
                        <p class="text-right">                    
                            <a href="#" onclick="verTelefone(1);">Ver telefone</a>
                        </p>
                        <h4 class="" style="display: none;" id="telefone_1"><i class="fa fa-phone"></i> (31) 95544-3322</h4>                
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
