<footer class="small">
    <div class="row">
        <div class="col-md-12">
            <a href="" class="">Política de Privacidade</a>                        
            <a href="" class="">Termo de Uso</a>                        
        </div>
    </div>
    <div class="row">
        <div class="col-md-6  col-md-offset-3 text-center">
            <p><?php echo $this->translate("Todos os direitos reservados"); ?></p>
        </div>                    
    </div>
</footer>