<?php
    $frontController = Zend_Controller_Front::getInstance()->getRequest();
    $module = $frontController->getModuleName();
    $controller = $frontController->getControllerName();
?>
<nav class="navbar navbar-default">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url(array('controller' => 'index'), null, true); ?>">GUIASARZEDO</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <!--
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>            
            </ul>
            -->
            <?php if ($module === 'site' && $controller !== 'index') : ?>
            <form class="navbar-form navbar-left" role="search" method="get" action="<?php echo $this->url(array('controller' => 'busca')); ?>">
                <div class="form-group">
                    <label for="exampleInputEmail2" class="sr-only">Produto ou Serviço</label>
                    <input type="text" class="form-control" name="busca" placeholder="Digite o Produto ou Serviço...">
                </div>
                <button type="submit" class="btn btn-primary">Buscar <i class="fa fa-search"></i></button>
            </form>
            <?php endif; ?>

            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="<?php echo $this->url(array(
                        'controller' => 'cadastro'
                    ), null, true); ?>" class="">Quero me cadastrar <i class="fa fa-plus"></i></a>
                </li>
                <!--
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                </li>
                -->
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>