<section>
    <div class="row">
        <div class="col-md-12">
            <h1><?php echo $this->translate("Dicas de Segurança"); ?></h1>
            <hr />
        </div>
    </div>    
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                	<p>O GuiaSarzedo conta com medidas para impedir anúncios sem credibilidade. E sua iniciativa também é muito importante para garantir a você mais segurança em uma transação.</p>
                	<p>Confira algumas dicas importantes disponibilizadas pelo ZAP:</p>
                	<p>Desconfie de ofertas com o preço abaixo de mercado;</p>
                	<p>Nunca faça depósitos ou realize adiantamentos sem ter certeza da idoneidade do anunciante;</p>
                	<p>Confira a veracidade do endereço e do telefone do anunciante;</p>
                	<p>Verifique cuidadosamente o estado de conservação e funcionamento do produto ou serviço, eventuais garantias vigentes, notas fiscais e outros documentos;</p>
                	<p>Evite fornecer seu endereço ou marcar encontros em locais isolados ou de difícil acesso, opte por locais movimentados e que tenham um mínimo de segurança para as negociações, pagamento e/ou entrega do produto ou serviço;</p>
                	<p>Certifique-se de que o produto será entregue após o pagamento efetuado.</p>
                </div>
            </div>            
        </div>
    </div>
</section>