<section>
    <div class="row">
        <div class="col-md-12">
            <h1><?php echo $this->translate("Perguntas Mais Frequentes (FAQ)"); ?></h1>
            <hr />
        </div>
    </div>    
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">CADASTRO

1) Como faço para me cadastrar no site?

2) Como confirmar meu cadastro?

3) Como faço para alterar o e-mail de cadastro?

4) Como faço para alterar o nome de cadastro?

5) Como excluir meu cadastro?

6) Como faço para receber uma nova senha?


ANÚNCIOS PARTICULARES

1) Como cadastrar um anúncio?

2) Como concluir um anúncio que já está cadastrado?

3) Como excluir um anúncio?

4) Como reativar um anúncio que esta inativo?

5) Como incluir as fotos em meu anúncio?

6) Qual é o prazo para que meu anúncio seja publicado?

7) Como visualizar o contato de um interessado?

8) Quais os prazos de confirmação de pagamento?


ANUNCIANTES PLANOS CORPORATIVOS

1) Como cadastrar um anúncio?

2) Como incluir fotos?

3) Como faço para editar um anúncio?

4) Como faço para excluir um anúncio?

5) Como faço para inativar um anúncio?

6) Como faço para incluir um anúncio em Destaque?

7) Como faço para excluir um anúncio de Destaque?

8) Como faço para incluir um anúncio de Super Destaque?

9) Como faço para excluir um anúncio de Super Destaque?

10) Como faço para alterar o Super Destaque anúncio?

11) Como faço para cadastrar um novo usuário de acesso?

12) Como faço para visualizar os contatos dos interessados em meus anúncios?

13) Como faço para incluir o logotipo da empresa?

14) Como faço para alterar o nome fantasia?

15) Como faço para alterar o telefone de contato?

16) Como faço para visualizar o relatório de retorno?

17) Como faço para imprimir o boleto?

18) Como faço para gerar um novo boleto?

19) Como faço alterar o meu plano?

20) Como cancelar o meu plano?

21) Qual o significado da informação “Preço no ZAP” na extranet?

22) Como faço para alterar o código do anúncio?


ANUNCIANTES PLANO LIGHT

1) Quando o meu plano estará disponível para inserção das ofertas?

2) Como cadastrar um anúncio?

3) Como incluir fotos?

4. Como faço para editar um anúncio?

5) Como faço para excluir um anúncio?

6) Como faço para inativar um anúncio?

7) Como faço para incluir um anúncio em Destaque?

8) Como faço para excluir um anúncio de Destaque?

9) Como faço para cadastrar um novo usuário de acesso?

10) Como faço para visualizar os contatos dos interessados em meus anúncios?

11) Como faço para incluir o logotipo da empresa?

12) Como faço para alterar o nome fantasia?

13) Como faço para alterar o telefone de contato?

14) Como faço para visualizar o relatório de retorno?

15) Como alterar o meu plano?

16) Como cancelar o meu plano?

17) Como reativar um plano cancelado?

18) Qual o significado da informação “Preço no ZAP” na extranet?

19) Como faço para alterar o código do anúncio?


PERGUNTAS ADICIONAIS

1) Como faço para alterar o plano contratado e a forma de pagamento do anúncio que ainda não finalizei?

2) Como faço para contatar o anunciante?

3) Gostaria de saber por que algumas opções do site ficam desabilitadas ou indisponíveis?

4) Como faço para buscar um anúncio no ZAP?

5) Como faço para salvar os imóveis que mais me agradam?

6) Como posso receber novas sugestões de imóveis?


CADASTRO

1) Como faço para me cadastrar no site?

Clique na opção “Cadastre-se”, na parte superior à direita. Informe os dados solicitados e clique em “Cadastrar”.

2) Como confirmar meu cadastro?

Para confirmar o cadastro realizado no portal, acesse a caixa de entrada do seu e-mail. Verifique, abra a mensagem enviada pelo ZAP e clique no link "Clique aqui, para confirmar o seu cadastro". Após a confirmação, acesse o site novamente: www.zapimoveis.com.br, clique no campo "Login" e informe o e-mail e senha para que o acesso seja disponibilizado.

3) Como faço para alterar o e-mail de cadastro?

Para alterar o seu e-mail de cadastro envie um e-mail para atendimento@zapcorp.com.br, contendo nome, e-mail atual de cadastro e e-mail para alteração, sua solicitação será atendida em até 72 horas úteis.

4) Como faço para alterar o nome de cadastro?

Para alterar seu nome, acesse o seu cadastro pelo site www.zapimoveis.com.br, selecione "Minha Conta", depois “Editar Cadastro”. O campo ficará disponível ao clicar na opção “Corrigir”. Após a alteração, o prazo de atualização do site é de 2 a 4 horas.

5) Como excluir meu cadastro?

Informamos que o cadastro no ZAP é inteiramente gratuito. Para que possamos excluir o mesmo, por favor, nos envie sua solicitação para o e-mail: atendimento@zapcorp.com.br. Desta forma, sua solicitação será atendida para a exclusão em até 48 horas úteis.

6) Como receber uma nova senha?

Para receber uma nova senha, entre em nosso site www.zapimoveis.com.br, digite o seu e-mail na área de “Login” e clique na opção "Esqueci Minha Senha".

Voltar ao topo

ANÚNCIOS PARTICULARES

1) Como cadastrar um anúncio?

Para fazer o seu anúncio, acesse www.zap.com.br/imoveis e clique em “Anuncie já, clique aqui para anunciar”. Preencha todos os campos obrigatórios e, ao final, o plano desejado. Caso não tenha cadastro no ZAP, pedimos que preencha as informações solicitadas na primeira etapa de cadastramento ao final da página.

Se preferir consulte o vídeo com o passo a passo de como anunciar no ZAP. https://www.youtube.com/watch?v=T0-YasP8zbw

2) Como concluir um anúncio que já está cadastrado?

Para concluir o anúncio, acesse o seu cadastro no campo “Login”, clique em “Minha Conta” e depois “Editar Anúncios”. Em seguida clique em "Completar Cadastro". Salientamos que todos os campos com (*) são obrigatórios o preenchimento. Após passar por todas as etapas, clique em "Finalizar".

3) Como excluir um anúncio?

Para excluir o anúncio, acesse o seu cadastro no campo “Login” e clique em “Minha Conta”, “Editar Anúncios” e, em seguida, clique em “Excluir”.

4) Como reativar um anúncio que está inativo?

Acesse o seu cadastro no campo “Login”, clique em “Minha Conta”, “Editar Anúncios” e depois clique em "Reativar".

5) Como incluir as fotos em meu anúncio?

Para incluir as fotos, acesse o seu cadastro no campo “Login”, clique na opção “Editar Anúncios” e, em seguida, "Editar Anúncio".

Ao final da página, deverá clicar em “Continuar”, em seguida “Continuar” novamente. Na próxima etapa clique, na opção “Adicionar Foto” para localizar em seu computador as imagens que deseja incluir em seu anúncio. Depois, clique em "Enviar" para fazer o upload das fotos.

Para alterar a ordem dessa lista, clique na foto, arraste e a solte na posição desejada. Ao terminar clique, em "Finalizar".

As fotos devem estar no formato JPG, GIF ou PNG e com peso máximo de 10MB (cada foto). As dimensões recomendadas de 580 x 435 pixels (largura x altura).

Utilize fotos, preferencialmente, na posição horizontal.

6) Qual é o prazo para que meu anúncio seja publicado?

Informamos que após a inclusão do anúncio em nosso site o prazo de disponibilização é de 4 a 72 horas, dependendo da forma de pagamento escolhida.

7) Como visualizar o contato de um interessado?

Para entrar em contato com o interessado em seu anúncio, acesse www.zapimoveis.com.br, insira os dados de login e clique em “Minha Conta”, “Editar Anúncio”, em seguida, selecione "Relatório de Retorno", localizado na parte superior da página.

Informamos que, os dados do interessado também são encaminhados para o e-mail de cadastro e este contato fica a critério do mesmo.

8) Quais os prazos de confirmação de pagamento?

O anúncio feito por meio do cartão de crédito será disponibilizado em até 4 horas no ZAP com status de “Aguardando Confirmação de Pagamento”. Se o pagamento for realizado com boleto bancário, informamos que seu anúncio será disponibilizado após a confirmação deste pagamento, o mesmo pode ocorrer no prazo máximo de 72 horas úteis.

Voltar ao topo</p>
                </div>
            </div>            
        </div>
    </div>
</section>
