<section>
    <div class="row">
        <div class="col-md-12">
            <h3><?php echo $this->translate("Novo Cadastro"); ?></h3>
            <hr />
        </div>
    </div>    
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <?php echo $this->formSiteCadastro; ?>
                </div>
            </div>            
        </div>
    </div>
</section>