<?php echo $this->doctype(); ?>

<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Guia Sarzedo - Guia de Produtos e Serviços de SARZEDO e região</title>

        <!-- CSS -->
        <link href="<?php echo $this->baseUrl("views/css/bootstrap.min.css"); ?>" rel="stylesheet">
        <link href="<?php echo $this->baseUrl("views/css/style.css"); ?>" rel="stylesheet">        
        <link href="<?php echo $this->baseUrl("views/css/bootstrap-theme.min.css"); ?>" rel="stylesheet">
        <link href="<?php echo $this->baseUrl("views/css/font-awesome.min.css"); ?>" rel="stylesheet">
        <link href="<?php echo $this->baseUrl("views/css/font-awesome.min.css"); ?>" rel="stylesheet">
        <link href="<?php echo $this->baseUrl("views/css/jquery-ui.min.css"); ?>" rel="stylesheet">
        <link href="<?php echo $this->baseUrl("views/css/jquery-ui.theme.min.css"); ?>" rel="stylesheet">
        <link href="<?php echo $this->baseUrl("views/css/jquery-ui.structure.min.css"); ?>" rel="stylesheet">
        <link href="<?php //echo $this->baseUrl("views/css/jquery.tagedit.css"); ?>" rel="stylesheet">
        
        <!-- tag editor css -->
        <link href="<?php echo $this->baseUrl("views/js/tagEditor/jquery.tag-editor.css"); ?>" rel="stylesheet">
        
        <!-- Js -->
        <script src="<?php echo $this->baseUrl("views/js/jquery.min.js"); ?>"></script>
        <script src="<?php echo $this->baseUrl("views/js/jquery-ui.min.js"); ?>"></script>
        <script src="<?php echo $this->baseUrl("views/js/bootstrap.min.js"); ?>"></script>
        <!-- MaskedInput -->
        <script src="<?php echo $this->baseUrl("views/js/jquery.maskedinput.js"); ?>"></script> 
        
        <!-- tag editor js -->
        <script src="<?php echo $this->baseUrl("views/js/tagEditor/jquery.tag-editor.min.js"); ?>"></script>
        <script src="<?php //echo $this->baseUrl("views/js/tagEditor/jquery.tagedit.js"); ?>"></script>
        <script src="<?php echo $this->baseUrl("views/js/tagEditor/jquery.caret.min.js"); ?>"></script>
        
        
        <?php echo $this->headScript(); ?>

    </head>
    <body>
        <?php echo $this->partial('partials/menu.phtml'); ?>

        <!--div class="container" id=""-->

            <?php echo $this->layout()->content; ?>

            <?php //echo $this->partial('partials/buscas-mais-populares.phtml'); ?>

        <!--/div--> <!-- /container --> 

        <?php echo $this->partial('partials/footer.phtml'); ?> 

        <?php echo $this->inlineScript() ?>
    </body>
</html>
