<section>
    <div class="row">
        <div class="col-md-12">
            <h1><?php echo $this->translate("Quem Somos"); ?></h1>
            <hr />
        </div>
    </div>    
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                   	<p>GuiaSarzedo é o guia internet de produtos e serviços de Sarzedo e região. É um dos primeiros do país a ter como foco o mercado local. Desde que entrou no ar em 01 de novembro de 2015, oferece ao internauta, informações sobre a cidade, indicando os melhores profissionais, empresas e outros serviços de interesse do público.</p>
                	<p>São mais de ... de page views por mês, mais de ... usuários únicos e uma grande base de dados que garante ao GuiaSarzedo o título de maior portal online da cidade de Sarzedo.</p>
                	<p>O GuiaSarzedo dispõe hoje de uma equipe multidisciplinar que produz todo o conteúdo do portal. São jornalistas, fotógrafos, desenvolvedores e profissionais de marketing que trabalham initerruptamente para entregar os melhores resultados aos nossos visitantes.</p>
                	<p>Desde 2015, o GuiaSarzedo fornece aos usuários acesso gratuito a milhões de resultados de produtos e serviços. Como a principal rede de anúncios utilizando o modelo pague-por-desempenho, o GuiaSarzedo direciona milhões de usuários as melhores empresas e prestadores de serviços em todas as áreas.</p>
                	<p>O GuiaSarzedo é uma empresa do SarzedoMais, é o mais completo, moderno e eficiente portal de classificados da internet da cidade de Sarzedo.</p>
                	<p>Ele traz os melhores caminhos para oferecer ao usuário a mais rápida solução entre a procura e o encontro do produto e o serviço ideal. Para qualquer pessoa, em qualquer lugar, por meio de ferramentas de buscas e os mais adequados filtros de pesquisa.</p>
                	<p>Fundada por Valdir Moura e Fernando Pires, o GuiaSarzedo é uma startup de classificados que possui escritório em Sarzedo e Belo Horizonte. Para mais informações sobre o GuiaSarzedo, visite o nosso blog, sala de imprensa ou entre em contato conosco.</p>
                	<br/><br/>
                	<p>Endereço:</p>
                	<p>Guia Sarzedo<br/>
                	Sarzedo/MG</p>
                </div>
            </div>            
        </div>
    </div>
</section>
